version: '3'
services:
  frontend:
    image: thomasmaged/app_frontend
    ports:
      - "8080:80"
    depends_on:
      - app  
    
  app:
    image: thomasmaged/app_backend
    depends_on:
      - db 
    ports:
      - "3000:3000"  

  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=personsDatabase
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
           
